require('dotenv').config({ path: '../../.env' })
const mongoose = require('mongoose')
const Skill    = require('../../src/models/Skill')
const { MONGODB_URI } = require('../../src/config/env')

const SKILLS = [
  // Programming & Tech
  { name: 'JavaScript',          category: 'Programming' },
  { name: 'Python',              category: 'Programming' },
  { name: 'React',               category: 'Programming' },
  { name: 'Node.js',             category: 'Programming' },
  { name: 'TypeScript',          category: 'Programming' },
  { name: 'SQL',                 category: 'Programming' },
  { name: 'Machine Learning',    category: 'Programming' },
  { name: 'Go',                  category: 'Programming' },
  { name: 'Rust',                category: 'Programming' },
  { name: 'Java',                category: 'Programming' },
  { name: 'C++',                 category: 'Programming' },
  { name: 'C#',                  category: 'Programming' },
  { name: 'Swift',               category: 'Programming' },
  { name: 'Kotlin',              category: 'Programming' },
  { name: 'PHP',                 category: 'Programming' },
  { name: 'Ruby',                category: 'Programming' },
  { name: 'Dart',                category: 'Programming' },
  { name: 'Flutter',             category: 'Programming' },
  { name: 'React Native',        category: 'Programming' },
  { name: 'Vue.js',              category: 'Programming' },
  { name: 'Angular',             category: 'Programming' },
  { name: 'Next.js',             category: 'Programming' },
  { name: 'Django',              category: 'Programming' },
  { name: 'FastAPI',             category: 'Programming' },
  { name: 'Docker',              category: 'Programming' },
  { name: 'Kubernetes',          category: 'Programming' },
  { name: 'AWS',                 category: 'Programming' },
  { name: 'Git & GitHub',        category: 'Programming' },
  { name: 'Linux / Shell',       category: 'Programming' },
  { name: 'Data Structures',     category: 'Programming' },
  { name: 'System Design',       category: 'Programming' },
  { name: 'Blockchain',          category: 'Programming' },
  { name: 'Cybersecurity',       category: 'Programming' },
  { name: 'Deep Learning',       category: 'Programming' },
  { name: 'Computer Vision',     category: 'Programming' },
  { name: 'NLP',                 category: 'Programming' },
  { name: 'Data Analysis',       category: 'Programming' },
  { name: 'Power BI',            category: 'Programming' },
  { name: 'Tableau',             category: 'Programming' },

  // Design
  { name: 'Figma',               category: 'Design' },
  { name: 'UI/UX Design',        category: 'Design' },
  { name: 'Adobe Illustrator',   category: 'Design' },
  { name: 'Adobe Photoshop',     category: 'Design' },
  { name: 'Adobe XD',            category: 'Design' },
  { name: 'Graphic Design',      category: 'Design' },
  { name: 'Logo Design',         category: 'Design' },
  { name: 'Motion Graphics',     category: 'Design' },
  { name: 'Brand Design',        category: 'Design' },
  { name: 'Typography',          category: 'Design' },
  { name: 'Color Theory',        category: 'Design' },
  { name: 'Canva',               category: 'Design' },
  { name: 'Video Editing',       category: 'Design' },
  { name: 'After Effects',       category: 'Design' },
  { name: 'Premiere Pro',        category: 'Design' },
  { name: 'Blender 3D',          category: 'Design' },
  { name: 'Illustration',        category: 'Design' },

  // Language
  { name: 'Spanish',             category: 'Language' },
  { name: 'Mandarin Chinese',    category: 'Language' },
  { name: 'French',              category: 'Language' },
  { name: 'Japanese',            category: 'Language' },
  { name: 'German',              category: 'Language' },
  { name: 'Hindi',               category: 'Language' },
  { name: 'Arabic',              category: 'Language' },
  { name: 'Portuguese',          category: 'Language' },
  { name: 'Italian',             category: 'Language' },
  { name: 'Korean',              category: 'Language' },
  { name: 'Russian',             category: 'Language' },
  { name: 'Turkish',             category: 'Language' },
  { name: 'Dutch',               category: 'Language' },
  { name: 'Swedish',             category: 'Language' },
  { name: 'Polish',              category: 'Language' },
  { name: 'Sign Language',       category: 'Language' },
  { name: 'Latin',               category: 'Language' },
  { name: 'Greek',               category: 'Language' },

  // Music
  { name: 'Guitar',              category: 'Music' },
  { name: 'Piano',               category: 'Music' },
  { name: 'Drums',               category: 'Music' },
  { name: 'Bass Guitar',         category: 'Music' },
  { name: 'Violin',              category: 'Music' },
  { name: 'Cello',               category: 'Music' },
  { name: 'Ukulele',             category: 'Music' },
  { name: 'Flute',               category: 'Music' },
  { name: 'Saxophone',           category: 'Music' },
  { name: 'Trumpet',             category: 'Music' },
  { name: 'Singing / Vocals',    category: 'Music' },
  { name: 'Music Production',    category: 'Music' },
  { name: 'Music Theory',        category: 'Music' },
  { name: 'DJing',               category: 'Music' },
  { name: 'Beat Making',         category: 'Music' },
  { name: 'Sound Design',        category: 'Music' },
  { name: 'Ableton Live',        category: 'Music' },
  { name: 'FL Studio',           category: 'Music' },

  // Business
  { name: 'Public Speaking',     category: 'Business' },
  { name: 'Excel / Spreadsheets', category: 'Business' },
  { name: 'Project Management',  category: 'Business' },
  { name: 'Product Management',  category: 'Business' },
  { name: 'Business Strategy',   category: 'Business' },
  { name: 'Entrepreneurship',    category: 'Business' },
  { name: 'Sales',               category: 'Business' },
  { name: 'Negotiation',         category: 'Business' },
  { name: 'Leadership',          category: 'Business' },
  { name: 'HR & Recruitment',    category: 'Business' },
  { name: 'Supply Chain',        category: 'Business' },
  { name: 'Operations',          category: 'Business' },

  // Marketing
  { name: 'Digital Marketing',   category: 'Marketing' },
  { name: 'SEO',                 category: 'Marketing' },
  { name: 'Content Marketing',   category: 'Marketing' },
  { name: 'Social Media',        category: 'Marketing' },
  { name: 'Email Marketing',     category: 'Marketing' },
  { name: 'Google Ads',          category: 'Marketing' },
  { name: 'Facebook Ads',        category: 'Marketing' },
  { name: 'Copywriting',         category: 'Marketing' },
  { name: 'Growth Hacking',      category: 'Marketing' },
  { name: 'Brand Strategy',      category: 'Marketing' },
  { name: 'Analytics',           category: 'Marketing' },
  { name: 'Affiliate Marketing', category: 'Marketing' },

  // Finance
  { name: 'Personal Finance',    category: 'Finance' },
  { name: 'Stock Trading',       category: 'Finance' },
  { name: 'Crypto & Web3',       category: 'Finance' },
  { name: 'Accounting',          category: 'Finance' },
  { name: 'Financial Modeling',  category: 'Finance' },
  { name: 'Investing',           category: 'Finance' },
  { name: 'Budgeting',           category: 'Finance' },
  { name: 'Tax Planning',        category: 'Finance' },
  { name: 'Real Estate',         category: 'Finance' },
  { name: 'Options Trading',     category: 'Finance' },
  { name: 'Forex Trading',       category: 'Finance' },

  // Arts & Crafts
  { name: 'Drawing',             category: 'Arts & Crafts' },
  { name: 'Painting',            category: 'Arts & Crafts' },
  { name: 'Watercolor',          category: 'Arts & Crafts' },
  { name: 'Sketching',           category: 'Arts & Crafts' },
  { name: 'Digital Art',         category: 'Arts & Crafts' },
  { name: 'Photography',         category: 'Arts & Crafts' },
  { name: 'Film Making',         category: 'Arts & Crafts' },
  { name: 'Creative Writing',    category: 'Arts & Crafts' },
  { name: 'Screenwriting',       category: 'Arts & Crafts' },
  { name: 'Pottery',             category: 'Arts & Crafts' },
  { name: 'Knitting',            category: 'Arts & Crafts' },
  { name: 'Sewing',              category: 'Arts & Crafts' },
  { name: 'Woodworking',         category: 'Arts & Crafts' },
  { name: 'Jewelry Making',      category: 'Arts & Crafts' },
  { name: 'Origami',             category: 'Arts & Crafts' },
  { name: 'Calligraphy',         category: 'Arts & Crafts' },
  { name: 'Comic Art',           category: 'Arts & Crafts' },
  { name: 'Manga Drawing',       category: 'Arts & Crafts' },

  // Sports & Fitness
  { name: 'Yoga',                category: 'Sports & Fitness' },
  { name: 'Meditation',          category: 'Sports & Fitness' },
  { name: 'Weight Training',     category: 'Sports & Fitness' },
  { name: 'Running',             category: 'Sports & Fitness' },
  { name: 'Swimming',            category: 'Sports & Fitness' },
  { name: 'Cycling',             category: 'Sports & Fitness' },
  { name: 'Martial Arts',        category: 'Sports & Fitness' },
  { name: 'Boxing',              category: 'Sports & Fitness' },
  { name: 'Brazilian Jiu-Jitsu', category: 'Sports & Fitness' },
  { name: 'Football',            category: 'Sports & Fitness' },
  { name: 'Basketball',          category: 'Sports & Fitness' },
  { name: 'Tennis',              category: 'Sports & Fitness' },
  { name: 'Badminton',           category: 'Sports & Fitness' },
  { name: 'Table Tennis',        category: 'Sports & Fitness' },
  { name: 'Cricket',             category: 'Sports & Fitness' },
  { name: 'Pilates',             category: 'Sports & Fitness' },
  { name: 'Calisthenics',        category: 'Sports & Fitness' },
  { name: 'Dance',               category: 'Sports & Fitness' },
  { name: 'Hip Hop Dance',       category: 'Sports & Fitness' },
  { name: 'Salsa',               category: 'Sports & Fitness' },
  { name: 'Climbing',            category: 'Sports & Fitness' },
  { name: 'Surfing',             category: 'Sports & Fitness' },
  { name: 'Skateboarding',       category: 'Sports & Fitness' },

  // Cooking
  { name: 'Baking',              category: 'Cooking' },
  { name: 'Pastry & Desserts',   category: 'Cooking' },
  { name: 'Bread Making',        category: 'Cooking' },
  { name: 'Vegetarian Cooking',  category: 'Cooking' },
  { name: 'Vegan Cooking',       category: 'Cooking' },
  { name: 'Italian Cuisine',     category: 'Cooking' },
  { name: 'Indian Cuisine',      category: 'Cooking' },
  { name: 'Japanese Cuisine',    category: 'Cooking' },
  { name: 'Chinese Cuisine',     category: 'Cooking' },
  { name: 'Mexican Cuisine',     category: 'Cooking' },
  { name: 'BBQ & Grilling',      category: 'Cooking' },
  { name: 'Cocktail Making',     category: 'Cooking' },
  { name: 'Coffee Brewing',      category: 'Cooking' },
  { name: 'Knife Skills',        category: 'Cooking' },
  { name: 'Meal Prepping',       category: 'Cooking' },

  // Science
  { name: 'Mathematics',         category: 'Science' },
  { name: 'Statistics',          category: 'Science' },
  { name: 'Physics',             category: 'Science' },
  { name: 'Chemistry',           category: 'Science' },
  { name: 'Biology',             category: 'Science' },
  { name: 'Astronomy',           category: 'Science' },
  { name: 'Neuroscience',        category: 'Science' },
  { name: 'Psychology',          category: 'Science' },
  { name: 'Calculus',            category: 'Science' },
  { name: 'Linear Algebra',      category: 'Science' },
  { name: 'Robotics',            category: 'Science' },
  { name: 'Electronics',         category: 'Science' },
  { name: 'Arduino',             category: 'Science' },
  { name: 'Raspberry Pi',        category: 'Science' },

  // Other
  { name: 'Chess',               category: 'Other' },
  { name: 'Poker',               category: 'Other' },
  { name: 'Speed Reading',       category: 'Other' },
  { name: 'Memory Techniques',   category: 'Other' },
  { name: 'Touch Typing',        category: 'Other' },
  { name: 'Journaling',          category: 'Other' },
  { name: 'Mindfulness',         category: 'Other' },
  { name: 'Time Management',     category: 'Other' },
  { name: 'Habit Building',      category: 'Other' },
  { name: 'Gardening',           category: 'Other' },
  { name: 'Astrology',           category: 'Other' },
  { name: "Rubik's Cube",        category: 'Other' },
  { name: 'Home Repair & DIY',   category: 'Other' },
  { name: 'Car Maintenance',     category: 'Other' },
]

const seed = async () => {
  await mongoose.connect(MONGODB_URI)
  console.log('✅  Connected to MongoDB')

  await Skill.deleteMany({})
  console.log('🗑️   Cleared existing skills')

  const skills = await Skill.insertMany(SKILLS)
  console.log(`✅  Inserted ${skills.length} skills across ${new Set(SKILLS.map(s => s.category)).size} categories`)
  console.log('\n🌱  Seed complete!\n')

  await mongoose.disconnect()
  process.exit(0)
}

seed().catch(err => {
  console.error('❌  Seed failed:', err)
  process.exit(1)
})